amcl:
  ros__parameters:
    use_sim_time: true

    # Frame IDs
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"

    # Motion Model Parameters (Odometry model)
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    alpha1: 0.2  # rot_noise from rot
    alpha2: 0.2  # rot_noise from trans
    alpha3: 0.2  # trans_noise from trans
    alpha4: 0.2  # trans_noise from rot

    # Particle Filter Parameters
    # --- PERFORMANCE TUNING ---
    # These values are kept lower to reduce computational load, which is important
    # when using a Raspberry Pi, the common companion for the LD06 LiDAR.
    max_particles: 1000
    min_particles: 200
    resample_interval: 2
    transform_tolerance: 0.5
    update_min_a: 0.5 # radians
    update_min_d: 0.5 # meters

    # Laser Model Parameters (Sensor model)
    laser_model_type: "likelihood_field"

    # --- KEY CHANGE for LD06 LiDAR ---
    # The LD06 datasheet specifies a maximum effective range of 12 meters.
    # Setting this accurately prevents the algorithm from considering invalid, long-range noise.
    # Original: 100.0
    laser_max_range: 12.0

    # --- KEY CHANGE for LD06 LiDAR ---
    # The LD06 has a minimum range of ~0.02m. Setting this slightly higher
    # helps reject erroneous readings from points too close to the robot's center.
    # Original: -1.0
    laser_min_range: 0.10

    # --- KEY CHANGE for LD06 LiDAR ---
    # The LD06 provides a full 360-degree scan. Using more beams can improve
    # localization accuracy at the cost of higher CPU usage. 180 is a good
    # starting balance. You can increase this (e.g., to 360) if your system
    # can handle it, or decrease it if you still see performance issues.
    # Original: 60
    max_beams: 180

    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5
    sigma_hit: 0.2
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    do_beamskip: false # Beam skipping is less necessary with a lower max_beams count

    # Other Parameters
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    save_pose_rate: 0.5
    tf_broadcast: true
    scan_topic: scan

    # Initial Pose
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
